name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-all:

    runs-on: macos-latest

    env:
      WIRE_SPEC_BUILD_MAC_ARM: true

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run
        run: make all
      - name: Archive linux cli
        uses: actions/upload-artifact@v3
        with:
          name: wire-spec-cli-linux
          path: compiler/cli/build/bin/linuxX64/releaseExecutable/cli.kexe
      - name: Archive macos cli
        uses: actions/upload-artifact@v3
        with:
          name: wire-spec-cli-macos-x86
          path: compiler/cli/build/bin/macosX64/releaseExecutable/cli.kexe
      - name: Archive macosArm cli
        uses: actions/upload-artifact@v3
        with:
          name: wire-spec-cli-macos-arm64
          path: compiler/cli/build/bin/macosArm64/releaseExecutable/cli.kexe
      - name: Archive windows cli
        uses: actions/upload-artifact@v3
        with:
          name: wire-spec-cli-windows
          path: compiler/cli/build/bin/mingwX64/releaseExecutable/cli.exe
      - name: Archive vscode extension
        uses: actions/upload-artifact@v3
        with:
          name: wire-spec-client-vscode
          path: lsp/node/client/build/wire-spec-client-vscode-*.vsix
